# Generated by Django 5.2.4 on 2025-08-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("size", models.CharField(max_length=3)),
                ("content", models.CharField(null=True)),
                ("uploaded_image", models.ImageField(blank=True, upload_to="images/")),
            ],
        ),
    ]
