# Generated by Django 5.2.4 on 2025-08-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sh_shop", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="gender",
            field=models.CharField(
                choices=[("male", "남성"), ("female", "여성"), ("unisex", "공용")],
                default="unisex",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
