# Generated by Django 5.2.4 on 2025-08-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sh_shop", "0004_alter_post_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[
                    ("top", "상의"),
                    ("bottom", "하의"),
                    ("outer", "아우터"),
                    ("shoes", "신발"),
                    ("etc", "잡화"),
                ],
                max_length=20,
            ),
        ),
    ]
