# Generated by Django 5.2.4 on 2025-08-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sh_shop", "0005_alter_post_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(default="내용없음"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
