# Generated by Django 5.2.4 on 2025-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sh_shop", "0006_alter_post_content_alter_post_uploaded_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.TextField(),
        ),
    ]
