# Generated by Django 5.2.4 on 2025-08-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sh_shop", "0007_alter_post_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.IntegerField(),
        ),
    ]
